FROM ghcr.io/cross-rs/armv7-unknown-linux-gnueabihf@sha256:4a08bebb60f08d52c1885b643a768f163c7318c05f91cf119f6c02855ea52699
RUN curl --fail --location --proto '=https' --tlsv1.2 https://github.com/openssl/openssl/releases/download/openssl-3.5.6/openssl-3.5.6.tar.gz -o /tmp/openssl.tar.gz \
 && printf '%s  %s\n' deae7c80cba99c4b4f940ecadb3c3338b13cb77418409238e57d7f31f2a3b736 /tmp/openssl.tar.gz | sha256sum -c - \
 && mkdir /tmp/openssl-src \
 && tar -xzf /tmp/openssl.tar.gz --strip-components=1 -C /tmp/openssl-src \
 && cd /tmp/openssl-src \
 && ./Configure linux-armv4 --cross-compile-prefix=arm-linux-gnueabihf- no-shared no-tests --prefix=/opt/openssl-armv7 --openssldir=/etc/ssl \
 && make -j4 \
 && make install_sw \
 && rm -rf /tmp/openssl-src /tmp/openssl.tar.gz
ENV OPENSSL_DIR=/opt/openssl-armv7 OPENSSL_STATIC=1
